import {newId} from './ids';
export {};
const records=document.querySelector('#admin-records')!;const status=document.querySelector('#admin-status')!;const identity=document.querySelector('#admin-identity')!;
let collection='orders';let rows:Record<string,any>[]=[];let role='viewer';
function text(tag:string,value:string){const node=document.createElement(tag);node.textContent=value;return node;}
async function mutation(input:unknown){const response=await fetch('/api/admin/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const data=await response.json();if(!response.ok)throw new Error(data.error);return data;}
async function load(){records.textContent='Loading…';try{const r=await fetch(`/api/admin/?collection=${collection}`);const data=await r.json();if(!r.ok)throw new Error(data.error);identity.textContent=`Signed in as ${data.identity.email} · ${data.identity.role}`;role=data.identity.role;rows=data.rows;render()}catch(e){identity.textContent=(e as Error).message;records.textContent=''}}
function actionButton(label:string,fn:()=>Promise<void>){const b=text('button',label) as HTMLButtonElement;b.className='button small outline';b.addEventListener('click',async()=>{b.disabled=true;try{await fn();if(!status.querySelector('a'))status.textContent='Saved.';await load()}catch(e){status.textContent=(e as Error).message}finally{b.disabled=false}});return b}
function render(){records.replaceChildren();(document.querySelector('#catalogue-editor') as HTMLFormElement).hidden=collection!=='catalogue'||role!=='manager';if(!rows.length)records.append(text('p','No records yet.'));for(const row of rows){const card=text('article','');card.className='admin-row';card.append(text('h2',row.id));const details=text('pre',JSON.stringify(row,null,2));card.append(details);
 if(collection==='catalogue'&&role==='manager'){const edit=text('button','Edit next revision');edit.className='button small';edit.addEventListener('click',()=>{const product=JSON.parse(row.body);product.revision++;(document.querySelector('#catalogue-editor textarea') as HTMLTextAreaElement).value=JSON.stringify(product,null,2)});card.append(edit)}
 if((collection==='orders'||collection==='quotes')&&role!=='viewer'){
 const select=document.createElement('select');select.setAttribute('aria-label',`Progress for ${row.id}`);const statuses=collection==='orders'?['awaiting_confirmation','confirmed','in_production','ready_for_collection','dispatched','complete','on_hold']:['new','reviewing','quoted','closed'];statuses.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s.replaceAll('_',' ');select.append(o)});select.value=row.fulfilment_status||row.status;card.append(select,actionButton('Update progress',async()=>{await mutation({action:collection==='orders'?'order-status':'quote-status',id:row.id,status:select.value})}));
 if(collection==='orders'&&row.paid_cents>0&&row.paid_cents<row.total_cents&&!row.refunded_cents){card.append(actionButton('Create balance link',async()=>{const result=await mutation({action:'balance',id:row.id});const a=document.createElement('a');a.href=result.url;a.textContent='Open secure balance payment link';a.className='text-link';status.replaceChildren(a)}))}
 }
 if(collection==='orders'&&role==='manager'&&row.paid_cents>row.refunded_cents){
 const details=document.createElement('details');details.append(text('summary','Refund a settled payment'));const form=document.createElement('form');const payment=document.createElement('select');payment.setAttribute('aria-label','Payment to refund');for(const p of row.payments||[]){if(p.status!=='paid')continue;const option=document.createElement('option');option.value=p.id;option.textContent=`${p.id} · AUD ${(p.amount_cents/100).toFixed(2)}`;payment.append(option)}
 const amount=document.createElement('input');amount.type='number';amount.min='0.01';amount.step='0.01';amount.required=true;amount.placeholder='Amount in AUD';amount.setAttribute('aria-label','Refund amount in AUD');const reason=document.createElement('textarea');reason.required=true;reason.minLength=10;reason.maxLength=500;reason.placeholder='Reason for refund';reason.setAttribute('aria-label','Reason for refund');const confirm=document.createElement('label');confirm.className='inline-check';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.required=true;confirm.append(checkbox,text('span','I confirm the amount and authorise this refund.'));const submit=text('button','Process refund') as HTMLButtonElement;submit.type='submit';submit.className='button';form.append(payment,amount,reason,confirm,submit);form.style.display='grid';form.style.gap='15px';let key=newId();form.addEventListener('change',()=>{key=newId()});form.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;try{const result=await mutation({action:'refund',id:row.id,checkoutId:payment.value,amountCents:Math.round(Number(amount.value)*100),reason:reason.value,requestKey:key});status.textContent=`Refund ${result.refundId}: ${result.status}`;load()}catch(e){status.textContent=(e as Error).message}finally{submit.disabled=false}});details.append(form);card.append(details);
 }
 records.append(card)}}
document.querySelectorAll<HTMLButtonElement>('[data-collection]').forEach(b=>b.addEventListener('click',()=>{collection=b.dataset.collection!;load()}));
document.querySelector('#catalogue-editor')?.addEventListener('submit',async e=>{e.preventDefault();try{const product=JSON.parse((document.querySelector('#catalogue-editor textarea') as HTMLTextAreaElement).value);await mutation({action:'catalogue',product});status.textContent='Commercial configuration saved.';load()}catch(e){status.textContent=(e as Error).message}});
document.querySelector('#admin-export')?.addEventListener('click',()=>{if(!rows.length)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}));a.download=`cta-${collection}.json`;a.click();URL.revokeObjectURL(a.href)});
load();
