import {newId} from './ids';
import {products,findProduct} from '../data/catalogue';
type Selection={key:string;productId:string;quantity:number;requirements:string;fulfilment:string;options:string[]};
const $=<T extends Element=HTMLElement>(selector:string)=>document.querySelector<T>(selector);
const all=<T extends Element=HTMLElement>(selector:string)=>Array.from(document.querySelectorAll<T>(selector));
const read=<T>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}};
const save=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new Event('cta:selection'));return true}catch{toast('Your browser could not save this selection. Please enable local storage.');return false}};
const cart=():Selection[]=>{const c=read<Selection[]>('cta.selection',[]);return Array.isArray(c)?c.filter(x=>findProduct(x.productId)&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=10):[]};
const compare=():string[]=>{const c=read<string[]>('cta.compare',[]);return Array.isArray(c)?c.filter(id=>findProduct(id)).slice(0,4):[]};
function toast(message:string){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
function counts(){all('[data-cart-count]').forEach(e=>e.textContent=String(cart().reduce((sum,i)=>sum+i.quantity,0)));all<HTMLButtonElement>('.compare-add').forEach(b=>{b.textContent=compare().includes(b.dataset.id!)?'Added ✓':'Compare +';b.setAttribute('aria-pressed',String(compare().includes(b.dataset.id!)))})}
$('.menu-toggle')?.addEventListener('click',e=>{const b=e.currentTarget as HTMLButtonElement;const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));$('#main-nav')?.classList.toggle('open',open)});
all<HTMLButtonElement>('.compare-add').forEach(b=>b.addEventListener('click',()=>{let ids=compare();if(ids.includes(b.dataset.id!)){ids=ids.filter(x=>x!==b.dataset.id)}else{if(ids.length===4){toast('Your comparison has four trailers. Remove one on the comparison page first.');return}ids.push(b.dataset.id!)}save('cta.compare',ids);counts();toast('Comparison updated. View it from the Compare trailers link.')}));
let category=new URLSearchParams(location.search).get('category')||'all';
function filter(){const container=$('#catalogue');if(!container)return;const term=$<HTMLInputElement>('#search')?.value.trim().toLowerCase()||'';const cards=all<HTMLElement>('#catalogue .product-card');let n=0;cards.forEach(card=>{const visible=(category==='all'||card.dataset.category===category)&&card.dataset.search!.includes(term);card.hidden=!visible;if(visible)n++});const sort=$<HTMLSelectElement>('#sort')?.value;cards.sort((a,b)=>sort==='name-asc'?a.querySelector('h3')!.textContent!.localeCompare(b.querySelector('h3')!.textContent!):sort==='name-desc'?b.querySelector('h3')!.textContent!.localeCompare(a.querySelector('h3')!.textContent!):products.findIndex(p=>p.id===a.dataset.product)-products.findIndex(p=>p.id===b.dataset.product)).forEach(c=>container.append(c));$('#result-count')!.textContent=`${n} trailer ${n===1?'design':'designs'}`;$('#no-results')?.classList.toggle('hidden',n>0);all('[data-filter]').forEach(el=>el.classList.toggle('selected',(el as HTMLElement).dataset.filter===category));}
all<HTMLAnchorElement>('[data-filter]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();category=a.dataset.filter!;history.replaceState(null,'',category==='all'?'/shop/':`/shop/?category=${encodeURIComponent(category)}`);filter()}));$('#search')?.addEventListener('input',filter);$('#sort')?.addEventListener('change',filter);$('#reset-filters')?.addEventListener('click',()=>{category='all';$<HTMLInputElement>('#search')!.value='';history.replaceState(null,'','/shop/');filter()});filter();
all<HTMLButtonElement>('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{const img=$<HTMLImageElement>('.gallery-main img')!;img.src=`/images/${b.dataset.gallery}-1536.webp`;img.srcset='';all('[data-gallery]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)))}));
$('.gallery-main')?.addEventListener('click',()=>{const d=$<HTMLDialogElement>('#image-dialog');if(d){d.querySelector('img')!.src=$<HTMLImageElement>('.gallery-main img')!.currentSrc;d.showModal()}});$('#image-dialog button')?.addEventListener('click',()=>$<HTMLDialogElement>('#image-dialog')?.close());
$('#configuration')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement;const data=new FormData(form);const item:Selection={key:newId(),productId:form.dataset.id!,quantity:Number(data.get('quantity')),requirements:String(data.get('requirements')||''),fulfilment:String(data.get('fulfilment')||'discuss'),options:[]};if(!save('cta.selection',[...cart(),item]))return;counts();if((e as SubmitEvent).submitter?.getAttribute('value')==='quote')location.href='/quote/';else toast('Saved to your selection.');});
const node=(tag:string,text?:string,className?:string)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(className)n.className=className;return n};
function renderCart(){const container=$('#cart-items');if(!container)return;container.replaceChildren();const items=cart();if(!items.length){const el=node('div',undefined,'empty-state');el.append(node('h2','Your selection is ready for a trailer.'),node('p','Explore the range and save a design to get started.'));const a=node('a','Explore trailers','button') as HTMLAnchorElement;a.href='/shop/';el.append(a);container.append(el)}items.forEach(item=>{const p=findProduct(item.productId)!;const row=node('article',undefined,'cart-item');const img=document.createElement('img');img.src=`/images/${p.images[0]}-480.webp`;img.alt=p.name;img.width=480;img.height=320;const copy=node('div');const link=document.createElement('a');link.href=`/trailers/${p.slug}/`;link.append(node('h2',p.name));copy.append(link,node('p',item.requirements||'Requirements to be discussed','muted'),node('p',item.fulfilment==='delivery'?'Delivery quote requested':item.fulfilment==='collection'?'Collection enquiry':'Collection or delivery to discuss','muted'));const quantity=node('div',undefined,'quantity');const input=document.createElement('input');input.type='number';input.min='1';input.max='10';input.value=String(item.quantity);input.setAttribute('aria-label',`Quantity for ${p.name}`);input.addEventListener('change',()=>{if(!input.checkValidity()){input.reportValidity();return}save('cta.selection',cart().map(x=>x.key===item.key?{...x,quantity:Number(input.value)}:x));counts();renderCart()});const remove=node('button','Remove','subtle');remove.addEventListener('click',()=>{save('cta.selection',cart().filter(x=>x.key!==item.key));counts();renderCart()});quantity.append(input,remove);copy.append(quantity);row.append(img,copy);container.append(row)});$('#cart-totals')!.textContent=`${items.reduce((s,i)=>s+i.quantity,0)} trailer${items.reduce((s,i)=>s+i.quantity,0)===1?'':'s'} selected`;}
renderCart();
const comp=$('#comparison');if(comp){const ids=compare();if(!ids.length){comp.append(node('h2','Start with two designs.'),node('p','Use Compare on a trailer card to add it here.'))}else{const table=node('table',undefined,'compare-table');const body=document.createElement('tbody');const row=document.createElement('tr');row.append(node('th','Trailer design'));ids.forEach(id=>{const p=findProduct(id)!;const cell=node('td');const img=document.createElement('img');img.src=`/images/${p.images[0]}-480.webp`;img.alt=p.name;const a=document.createElement('a');a.href=`/trailers/${p.slug}/`;a.className='text-link';a.textContent=p.name;const remove=node('button','Remove','subtle');remove.addEventListener('click',()=>{save('cta.compare',compare().filter(x=>x!==id));location.reload()});cell.append(img,a,node('br'),remove);row.append(cell)});body.append(row);['Design shown','Ratings & dimensions','Price','Included equipment'].forEach((label,index)=>{const tr=document.createElement('tr');tr.append(node('th',label));ids.forEach(id=>tr.append(node('td',index===0?findProduct(id)!.pictured.join(', '):'Confirmed with your quote')));body.append(tr)});table.append(body);comp.append(table)}}
const quoteForm=$<HTMLFormElement>('#quote-form');if(quoteForm){const items=cart();if(items.length){const interest=quoteForm.elements.namedItem('productId') as HTMLSelectElement;interest.value=items[0].productId;const msg=quoteForm.elements.namedItem('message') as HTMLTextAreaElement;msg.value=items.map(i=>`${findProduct(i.productId)!.name} × ${i.quantity}: ${i.requirements||'Please help me confirm a configuration.'}`).join('\n\n');(quoteForm.elements.namedItem('fulfilment') as HTMLSelectElement).value=items[0].fulfilment;$('#quote-selection')?.append(node('h3','Your saved selection'),...items.map(i=>node('p',`${findProduct(i.productId)!.name} × ${i.quantity}`)))}quoteForm.addEventListener('submit',async e=>{e.preventDefault();const status=$('#quote-status')!;const button=quoteForm.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;status.textContent='Sending your enquiry…';try{const data=Object.fromEntries(new FormData(quoteForm));const response=await fetch('/api/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,items:cart(),consent:data.consent==='on'})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Your enquiry could not be sent. Please try again.');status.textContent=`Enquiry received. Your reference is ${result.reference}.`;quoteForm.reset();save('cta.selection',[]);counts()}catch(err){status.textContent=(err as Error).message;status.classList.add('error')}finally{button.disabled=false}})}
const order=$('#order-status');if(order){fetch('/api/order').then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);order.replaceChildren(node('h2',data.reference),node('p',`Payment: ${data.paymentStatus.replaceAll('_',' ')}`),node('p',`Progress: ${data.fulfilmentStatus.replaceAll('_',' ')}`),node('p',`Received: ${data.paidDisplay}. Remaining balance: ${data.balanceDisplay}.`))}).catch(e=>{order.textContent=e.message})}
counts();

if(document.querySelector('#configuration, #cart-items, #checkout-purchase'))import('./commercial-client');
// Progressive enhancement: expose the same visible catalogue filtering action to supporting browsers.
const modelContext=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
if(modelContext?.registerTool&&document.querySelector('#catalogue')){
 const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 Promise.resolve(modelContext.registerTool({name:'filter_trailer_catalogue',title:'Filter trailer catalogue',description:'Set the visible trailer category and search term, then return the matching trailer designs. This does not submit an enquiry or place an order.',inputSchema:{type:'object',properties:{search:{type:'string',maxLength:120},category:{type:'string',enum:['all','car-transporters','box-and-cage','enclosed','trade-and-gardening']}},required:['search','category'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const v=input as {search:unknown;category:unknown};if(!v||typeof v.search!=='string'||v.search.length>120||typeof v.category!=='string'||!['all','car-transporters','box-and-cage','enclosed','trade-and-gardening'].includes(v.category))throw new Error('Choose a valid search and category.');category=v.category;$<HTMLInputElement>('#search')!.value=v.search;filter();return{matches:all<HTMLElement>('#catalogue .product-card').filter(c=>!c.hidden).map(c=>({id:c.dataset.product,name:c.querySelector('h3')!.textContent}))}}},{signal:lifecycle.signal})).catch(()=>{});
}
if(quoteForm)fetch('/api/public-settings').then(async response=>{
 if(!response.ok)return;const data=await response.json();if(!data.turnstileSiteKey)return;
 const slot=document.createElement('div');slot.className='full';const token=document.createElement('input');token.type='hidden';token.name='turnstileToken';quoteForm.append(token);quoteForm.querySelector('button[type=submit]')!.before(slot);
 const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=()=>{const turnstile=(window as Window & {turnstile?:{render:(element:Element,options:unknown)=>void}}).turnstile;turnstile?.render(slot,{sitekey:data.turnstileSiteKey,action:'quote',callback:(value:string)=>{token.value=value},'expired-callback':()=>{token.value=''}})};document.head.append(script);
}).catch(()=>{});
