import {newId} from './ids';
import {money} from '../data/catalogue';
import type {Commercial} from './pricing';
type Saved={key:string;productId:string;quantity:number;requirements:string;fulfilment:string;options:string[];revision?:number};
const read=():Saved[]=>{try{const value=JSON.parse(localStorage.getItem('cta.selection')||'[]');return Array.isArray(value)?value:[]}catch{return[]}};
const el=(tag:string,value?:string,className?:string)=>{const e=document.createElement(tag);if(value)e.textContent=value;if(className)e.className=className;return e;};
const form=document.querySelector<HTMLFormElement>('#configuration');
let catalogue:Commercial[]=[];
function calculate(items:Saved[],mode='full'){
 let total=0,due=0;const lines=[];
 for(const item of items){const p=catalogue.find(p=>p.id===item.productId);if(!p?.enabled)throw new Error('A confirmed quote is needed for one or more trailers.');if(item.revision!==p.revision)throw new Error('A trailer configuration has changed. Please review it on the trailer page.');let price=p.priceCents+p.collection.feeCents;const selected=p.options.filter(o=>item.options.includes(o.id));if(selected.length!==item.options.length)throw new Error('An option has changed. Please review your configuration.');if(selected.some(o=>o.excludes.some(id=>item.options.includes(id))))throw new Error('These options cannot be combined.');price+=selected.reduce((s,o)=>s+o.priceCents,0);price*=item.quantity;total+=price;let payable=price;if(mode==='deposit'){if(p.deposit.type==='none')throw new Error('A deposit is not available for every trailer in this selection.');payable=p.deposit.type==='percent'?Math.round(price*p.deposit.basisPoints/10000):p.deposit.cents*item.quantity;if(payable>=price||payable<1)throw new Error('This deposit needs to be confirmed.');}due+=payable;lines.push({item,product:p,total:price,due:payable});}
 return{total,due,balance:total-due,lines};
}
function setupProduct(){if(!form)return;const p=catalogue.find(p=>p.id===form.dataset.id);if(!p?.enabled)return;
 const info=el('div',undefined,'notice');const summary=el('div');info.append(el('strong',`${money(p.priceCents)} incl. GST`),el('p','Configure your trailer. Collection charges and options are itemised below.'));form.prepend(info);
 const options=el('fieldset');options.append(el('legend','Optional equipment'));p.options.forEach(o=>{const label=el('label',undefined,'inline-check');const input=document.createElement('input');input.type='checkbox';input.name='optionIds';input.value=o.id;label.append(input,el('span',`${o.name} + ${money(o.priceCents)}`));options.append(label)});form.querySelector('.actions')!.before(options,summary);
 const fulfilment=form.elements.namedItem('fulfilment') as HTMLSelectElement;fulfilment.replaceChildren();const choice=document.createElement('option');choice.value='collection';choice.textContent=`Collect: ${p.collection.name}`;fulfilment.append(choice);
 const save=form.querySelector<HTMLButtonElement>('button[value=save]')!;save.textContent='Add to selection & checkout';
 const selected=()=>({key:newId(),productId:p.id,quantity:Number((form.elements.namedItem('quantity') as HTMLInputElement).value),requirements:(form.elements.namedItem('requirements') as HTMLTextAreaElement).value,fulfilment:'collection',options:Array.from(form.querySelectorAll<HTMLInputElement>('input[name=optionIds]:checked')).map(x=>x.value),revision:p.revision});
 const update=()=>{try{const item=selected();const quote=calculate([item]);summary.replaceChildren(el('p',`Trailer: ${money(p.priceCents*item.quantity)}`),...p.options.filter(o=>item.options.includes(o.id)).map(o=>el('p',`${o.name}: ${money(o.priceCents*item.quantity)}`)),el('p',`Collection: ${money(p.collection.feeCents*item.quantity)}`),el('strong',`Total ${money(quote.total)} incl. GST`));save.disabled=false;}catch(e){summary.textContent=(e as Error).message;save.disabled=true;}};
 form.addEventListener('change',update);update();
 form.addEventListener('submit',event=>{const submitter=(event as SubmitEvent).submitter;if(submitter?.getAttribute('value')!=='save')return;event.preventDefault();event.stopImmediatePropagation();try{const item=selected();calculate([item]);localStorage.setItem('cta.selection',JSON.stringify([...read(),item]));location.href='/cart/'}catch(e){summary.textContent=(e as Error).message}},true);
 const specBody=document.querySelector('.specs tbody');if(specBody&&Object.keys(p.specifications).length){specBody.replaceChildren(...Object.entries(p.specifications).map(([name,value])=>{const row=el('tr');row.append(el('th',name),el('td',value));return row}))}
}
function setupCart(){if(!document.querySelector('#cart-items')||!catalogue.length)return;const items=read();if(!items.length)return;const target=document.querySelector('#cart-totals')!;try{const priced=calculate(items);target.replaceChildren(el('p',`${items.reduce((s,i)=>s+i.quantity,0)} trailers selected`),el('strong',`Total: ${money(priced.total)} incl. GST`));const button=document.querySelector<HTMLAnchorElement>('#cart-quote')!;button.href='/checkout/';button.textContent='Continue to secure checkout ↗';}catch(e){target.append(el('p',(e as Error).message));}}
function setupCheckout(){const container=document.querySelector('#checkout-purchase');if(!container)return;const items=read();if(!items.length||!catalogue.length)return;
 let priced;try{priced=calculate(items);if(new Set(priced.lines.map(l=>l.product.collection.id)).size!==1)throw new Error('Please request a quote for trailers from different collection locations.')}catch(e){container.append(el('p',(e as Error).message));return}
 document.querySelector('#checkout-enquiry')?.setAttribute('hidden','');
 const checkout=document.createElement('form');const heading=el('h1','Your final review.');checkout.append(heading);
 const emailLabel=el('label','Email for your order');const email=document.createElement('input');email.type='email';email.name='email';email.required=true;email.autocomplete='email';emailLabel.append(email);checkout.append(emailLabel);
 const modeLabel=el('label','Payment');const mode=document.createElement('select');mode.name='mode';const full=document.createElement('option');full.value='full';full.textContent='Pay in full';mode.append(full);if(priced.lines.every(l=>l.product.deposit.type!=='none')){const deposit=document.createElement('option');deposit.value='deposit';deposit.textContent='Pay the approved deposit';mode.append(deposit)}modeLabel.append(mode);checkout.append(modeLabel);
 const summary=el('div',undefined,'notice');checkout.append(summary);const update=()=>{try{const value=calculate(items,mode.value);summary.replaceChildren(...value.lines.map(l=>el('p',`${l.product.name} × ${l.item.quantity}: ${money(l.total)} · collection at ${l.product.collection.name}`)),el('p',`Order total: ${money(value.total)} incl. GST`),el('strong',`Due now: ${money(value.due)}`),el('p',`Remaining balance: ${money(value.balance)}`))}catch(e){summary.textContent=(e as Error).message}};mode.addEventListener('change',update);update();
 const termsLabel=el('label',undefined,'inline-check');const terms=document.createElement('input');terms.type='checkbox';terms.required=true;termsLabel.append(terms,el('span','I have reviewed my configuration, collection details and purchase terms.'));checkout.append(termsLabel);const termsLink=document.createElement('a');termsLink.href='/terms/';termsLink.textContent='Read purchase terms';termsLink.className='text-link';checkout.append(termsLink);
 const submit=document.createElement('button');submit.type='submit';submit.className='button';submit.textContent='Continue to Stripe Checkout';checkout.append(submit);const feedback=el('p');feedback.setAttribute('role','status');checkout.append(feedback);container.append(checkout);
 checkout.style.display='grid';checkout.style.gap='22px';let requestKey=newId();let previous='';
 checkout.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;try{const value=calculate(items,mode.value);const input={email:email.value,items:items.map(i=>({productId:i.productId,quantity:i.quantity,optionIds:i.options,revision:i.revision,requirements:i.requirements})),paymentMode:mode.value,fulfilment:'collection',collectionId:value.lines[0].product.collection.id,expectedTotalCents:value.total};const fingerprint=JSON.stringify(input);if(previous&&previous!==fingerprint)requestKey=newId();previous=fingerprint;const response=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,requestKey})});const result=await response.json();if(!response.ok)throw new Error(result.error);const url=new URL(result.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw new Error('The payment link could not be verified.');location.assign(url.href)}catch(e){feedback.textContent=(e as Error).message;submit.disabled=false}});
}
if(form||document.querySelector('#cart-items')||document.querySelector('#checkout-purchase'))fetch('/api/catalogue').then(async response=>{if(!response.ok)return;const data=await response.json();catalogue=data.products;setupProduct();setupCart();setupCheckout()}).catch(()=>{});
window.addEventListener('cta:selection',()=>setTimeout(setupCart,0));
