import {z} from 'zod';
import type {Env} from './env';
export class HttpError extends Error {constructor(public status:number,message:string){super(message)}}
export const json=(data:unknown,status=200,headers:Record<string,string>={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
export function failure(error:unknown){if(error instanceof HttpError)return json({error:error.message},error.status);if(error instanceof z.ZodError)return json({error:'Please check the details and try again.',fields:error.issues.map(i=>i.path.join('.'))},400);console.error('request_failed',error instanceof Error?error.name:'unknown');return json({error:'We could not complete this request. Please try again shortly.'},503)}
export function sameOrigin(request:Request,env:Env){const origin=request.headers.get('Origin');if(!origin||origin!==new URL(env.APP_ORIGIN).origin)throw new HttpError(403,'This request must come from our website.');}
export async function body(request:Request,max=24000){if(!request.headers.get('content-type')?.includes('application/json'))throw new HttpError(415,'Please send a valid form request.');const text=await request.text();if(text.length>max)throw new HttpError(413,'Your request is too large.');try{return JSON.parse(text)}catch{throw new HttpError(400,'Please send a valid form request.')}}
export const sha256=async(text:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(x=>x.toString(16).padStart(2,'0')).join('');
export async function rateLimit(request:Request,env:Env,scope:string,limit=10){const ip=request.headers.get('CF-Connecting-IP')||'local';if(env.APP_ENV==='production'&&!env.RATE_LIMIT_SALT)throw new HttpError(503,'This service is being configured.');const key=await sha256(`${env.RATE_LIMIT_SALT||'local-only'}:${scope}:${ip}:${Math.floor(Date.now()/600000)}`);const result=await env.DB.prepare('INSERT INTO rate_limits (id,hits,expires_at) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET hits=hits+1 RETURNING hits').bind(key,Math.floor(Date.now()/1000)+1200).first<{hits:number}>();if(result!.hits>limit)throw new HttpError(429,'Please wait a few minutes before trying again.');}
export const safeToken=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
