import {products,findProduct,money} from '../data/catalogue';
import type {Commercial} from './pricing';
const q=<T extends Element=HTMLElement>(s:string,root:ParentNode=document)=>root.querySelector<T>(s);
const qa=<T extends Element=HTMLElement>(s:string,root:ParentNode=document)=>Array.from(root.querySelectorAll<T>(s));
const node=(tag:string,text='',className='')=>{const el=document.createElement(tag);el.textContent=text;el.className=className;return el};

// Details menus remain useful without JavaScript; enhancement adds dismissal and one-open-at-a-time.
qa<HTMLDetailsElement>('.nav-dropdown').forEach(menu=>{menu.addEventListener('toggle',()=>{if(menu.open)qa<HTMLDetailsElement>('.nav-dropdown').filter(x=>x!==menu).forEach(x=>x.open=false)});menu.addEventListener('keydown',event=>{if(event.key==='Escape'){menu.open=false;q<HTMLElement>('summary',menu)?.focus()}})});
document.addEventListener('click',event=>{qa<HTMLDetailsElement>('.nav-dropdown[open],.help-widget[open],.page-jump[open]').forEach(menu=>{if(!menu.contains(event.target as Node))menu.open=false})});
qa<HTMLAnchorElement>('.page-jump a').forEach(a=>a.addEventListener('click',()=>q<HTMLDetailsElement>('.page-jump')!.open=false));

// Accessible, keyboard-operated tabs for homepage, product information and locations.
qa('[data-tabs]').forEach(group=>{const tabs=qa<HTMLButtonElement>('[role=tab]',group);const activate=(tab:HTMLButtonElement)=>{tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;const panel=document.getElementById(t.getAttribute('aria-controls')!);if(panel)panel.hidden=!selected})};tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',event=>{let n=i;if(event.key==='ArrowRight'||event.key==='ArrowDown')n=(i+1)%tabs.length;else if(event.key==='ArrowLeft'||event.key==='ArrowUp')n=(i-1+tabs.length)%tabs.length;else if(event.key==='Home')n=0;else if(event.key==='End')n=tabs.length-1;else return;event.preventDefault();activate(tabs[n]);tabs[n].focus()})})});

const carousel=q('[data-carousel]');if(carousel){const slides=qa<HTMLElement>('[data-slide]',carousel),dots=qa<HTMLButtonElement>('[data-slide-to]',carousel);let current=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches;let timer:ReturnType<typeof setInterval>|undefined;const pause=q<HTMLButtonElement>('[data-slide-pause]',carousel)!;const show=(index:number)=>{current=(index+slides.length)%slides.length;slides.forEach((s,i)=>s.hidden=i!==current);dots.forEach((d,i)=>d.setAttribute('aria-pressed',String(i===current)));const progress=q<HTMLElement>('.hero-progress span',carousel)!;progress.style.width=`${(current+1)/slides.length*100}%`};const stop=()=>{clearInterval(timer);timer=undefined};const start=()=>{stop();if(!paused&&!document.hidden)timer=setInterval(()=>show(current+1),7000)};const label=()=>{pause.textContent=paused?'▶':'Ⅱ';pause.setAttribute('aria-label',paused?'Play slideshow':'Pause slideshow')};dots.forEach((d,i)=>d.addEventListener('click',()=>{show(i);paused=true;stop();label()}));q('[data-slide-next]',carousel)?.addEventListener('click',()=>{show(current+1);paused=true;stop();label()});q('[data-slide-prev]',carousel)?.addEventListener('click',()=>{show(current-1);paused=true;stop();label()});pause.addEventListener('click',()=>{paused=!paused;label();start()});carousel.addEventListener('mouseenter',stop);carousel.addEventListener('mouseleave',start);carousel.addEventListener('focusin',stop);carousel.addEventListener('focusout',event=>{if(!carousel.contains((event as FocusEvent).relatedTarget as Node))start()});document.addEventListener('visibilitychange',start);window.addEventListener('pagehide',stop);show(0);label();start()}

qa<HTMLElement>('[data-countdown]').forEach(el=>{const tick=()=>{const remaining=new Date(el.dataset.countdown!).getTime()-Date.now();if(remaining<=0){el.textContent='Offer ended';return}const seconds=Math.floor(remaining/1000);el.textContent=`Ends in ${Math.floor(seconds/86400)}d ${Math.floor(seconds%86400/3600)}h ${Math.floor(seconds%3600/60)}m ${seconds%60}s`};tick();const interval=setInterval(tick,1000);window.addEventListener('pagehide',()=>clearInterval(interval))});

// Drawer uses the same saved selections as full cart and checkout, never a second basket.
type Item={key:string;productId:string;quantity:number;requirements:string;fulfilment:string;options:string[];revision?:number};
const readCart=():Item[]=>{try{const items=JSON.parse(localStorage.getItem('cta.selection')||'[]');return Array.isArray(items)?items.filter(i=>i&&findProduct(i.productId)&&Number.isInteger(i.quantity)&&i.quantity>0&&i.quantity<=10).map(i=>({...i,requirements:typeof i.requirements==='string'?i.requirements:'',options:Array.isArray(i.options)?i.options:[]})):[]}catch{return[]}};
const drawer=q<HTMLDialogElement>('#cart-drawer');let opener:HTMLElement|null=null;
const drawCart=()=>{const container=q('#drawer-items');if(!container)return;container.replaceChildren();const items=readCart();q('#drawer-footer')!.hidden=!items.length;if(!items.length){const empty=node('div','','drawer-empty');empty.append(node('span','0','empty-count'),node('h3','Your cart is empty'),node('p','Save a trailer to start planning your order.'));const link=document.createElement('a');link.href='/shop/';link.className='button';link.textContent='Browse trailers';empty.append(link);container.append(empty);return}items.forEach(item=>{const p=findProduct(item.productId)!;const row=node('article','','drawer-item');const img=document.createElement('img');img.src=`/images/${p.images[0]}-480.webp`;img.alt=p.name;const body=node('div');const link=document.createElement('a');link.href=`/trailers/${p.slug}/`;link.append(node('h3',p.name));body.append(link,node('p',`${item.quantity} × · ${item.revision?'Review pricing at checkout':'Price by quotation'}`));if(item.requirements)body.append(node('p',item.requirements.slice(0,120),'muted'));const remove=node('button','Remove','subtle');remove.setAttribute('aria-label',`Remove ${p.name}`);remove.addEventListener('click',()=>{try{localStorage.setItem('cta.selection',JSON.stringify(readCart().filter(i=>i.key!==item.key)));window.dispatchEvent(new Event('cta:selection'));}catch{remove.textContent='Unable to update storage'}});body.append(remove);row.append(img,body);container.append(row)});q('#drawer-total')!.textContent=`${items.reduce((n,i)=>n+i.quantity,0)} trailer(s) selected. Confirmed prices and options appear at checkout.`};
const openCart=()=>{if(!drawer)return;opener=document.activeElement as HTMLElement;drawCart();drawer.showModal();document.body.classList.add('modal-open')};
qa('[data-open-cart]').forEach(button=>button.addEventListener('click',openCart));q('[data-close-cart]')?.addEventListener('click',()=>drawer?.close());drawer?.addEventListener('click',event=>{if(event.target===drawer){const rect=drawer.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right)drawer.close()}});drawer?.addEventListener('close',()=>{document.body.classList.remove('modal-open');opener?.focus()});window.addEventListener('cta:selection',()=>{drawCart();qa('[data-cart-count]').forEach(el=>el.textContent=String(readCart().reduce((n,i)=>n+i.quantity,0)))});window.addEventListener('cta:open-cart',openCart);window.addEventListener('storage',event=>{if(event.key==='cta.selection')window.dispatchEvent(new Event('cta:selection'))});

// Gallery controls share the product's approved image list and work inside the lightbox.
const galleryButtons=qa<HTMLButtonElement>('[data-gallery]');if(galleryButtons.length){let current=0;const update=(i:number)=>{current=(i+galleryButtons.length)%galleryButtons.length;galleryButtons[current].click();const image=q<HTMLImageElement>('.gallery-main img')!;image.alt=`${q('.detail-copy h1')?.textContent||'Trailer'} design view ${current+1}`;q('#gallery-count')!.textContent=`${String(current+1).padStart(2,'0')} / ${String(galleryButtons.length).padStart(2,'0')}`;const large=q<HTMLImageElement>('#image-dialog img');if(large)large.src=image.src};galleryButtons.forEach((b,i)=>b.addEventListener('click',()=>{current=i;q('#gallery-count')!.textContent=`${String(i+1).padStart(2,'0')} / ${String(galleryButtons.length).padStart(2,'0')}`}));qa('[data-image-next]').forEach(b=>b.addEventListener('click',()=>update(current+1)));qa('[data-image-prev]').forEach(b=>b.addEventListener('click',()=>update(current-1)));q('#image-dialog')?.addEventListener('keydown',event=>{if(event.key==='ArrowRight')update(current+1);if(event.key==='ArrowLeft')update(current-1)});}

// Read approved commerce once per page. Filters never infer a price or rating from a picture.
let commerce:Commercial[]=[];
const catalogueRoot=q('[data-catalogue-root]');
if(catalogueRoot){const cards=qa<HTMLElement>('#product-catalogue .product-card');const params=new URLSearchParams(location.search);const search=q<HTMLInputElement>('#catalogue-search')!;search.value=params.get('search')||'';const sort=q<HTMLSelectElement>('#catalogue-sort')!;if(['recommended','name-asc','name-desc'].includes(params.get('sort')||''))sort.value=params.get('sort')!;
const pageSize=12;let page=Math.max(1,Number(params.get('page'))||1);
qa<HTMLInputElement>('input[name=category]',catalogueRoot).forEach(input=>input.checked=(params.get('category')||'').split(',').includes(input.value));
const checkValues=(name:string)=>qa<HTMLInputElement>(`input[name="${name}"]:checked`,catalogueRoot).map(i=>i.value);
function apply(updateUrl=true){const cats=checkValues('category'),layouts=checkValues('layout'),features=checkValues('feature'),term=search.value.trim().toLowerCase();const min=Number(q<HTMLInputElement>('#min-price')?.value||0),max=Number(q<HTMLInputElement>('#max-price')?.value||Infinity);const matches=cards.filter(card=>{const p=findProduct(card.dataset.product!)!;const commercial=commerce.find(c=>c.id===p.id);const facetGroups=qa<HTMLElement>('[data-approved-facet]',catalogueRoot!).every(group=>{const vals=qa<HTMLInputElement>('input:checked',group).map(x=>x.value);return !vals.length||!!commercial&&vals.includes(commercial.specifications[group.dataset.approvedFacet!])});return (!cats.length||cats.includes(p.category))&&(!layouts.length||layouts.some(l=>p.pictured.includes(l)))&&(!features.length||features.some(f=>p.pictured.some(x=>x.toLowerCase().includes(f.toLowerCase()))))&&card.dataset.search!.includes(term)&&(!min&&max===Infinity||!!commercial&&commercial.priceCents>=min*100&&commercial.priceCents<=max*100)&&facetGroups});
matches.sort((a,b)=>{const pa=findProduct(a.dataset.product!)!,pb=findProduct(b.dataset.product!)!;if(sort.value==='name-asc')return pa.name.localeCompare(pb.name);if(sort.value==='name-desc')return pb.name.localeCompare(pa.name);if(sort.value.startsWith('price-')){const aPrice=commerce.find(p=>p.id===pa.id)?.priceCents,bPrice=commerce.find(p=>p.id===pb.id)?.priceCents;if(aPrice===undefined)return bPrice===undefined?0:1;if(bPrice===undefined)return -1;return sort.value==='price-asc'?aPrice-bPrice:bPrice-aPrice}return products.indexOf(pa)-products.indexOf(pb)});
const pages=Math.max(1,Math.ceil(matches.length/pageSize));page=Math.min(page,pages);cards.forEach(card=>card.hidden=true);matches.forEach((card,i)=>{q('#product-catalogue')!.append(card);card.hidden=i<(page-1)*pageSize||i>=page*pageSize});q('#catalogue-count')!.textContent=`${matches.length} ${matches.length===1?'Product':'Products'}`;q('#catalogue-empty')!.hidden=matches.length>0;
const pagination=q('#catalogue-pagination')!;pagination.replaceChildren();if(pages>1)for(let i=1;i<=pages;i++){const b=node('button',String(i));b.setAttribute('aria-label',`Page ${i}`);if(i===page)b.setAttribute('aria-current','page');b.addEventListener('click',()=>{page=i;apply();catalogueRoot!.scrollIntoView({block:'start'})});pagination.append(b)}
const active=q('#active-filters')!;active.replaceChildren();qa<HTMLInputElement>('input[type=checkbox]:checked',catalogueRoot!).forEach(input=>{const b=node('button',`${input.closest('label')?.querySelector('span')?.textContent||input.value} ×`);b.setAttribute('aria-label',`Remove filter ${input.value}`);b.addEventListener('click',()=>{input.checked=false;page=1;apply()});active.append(b)});
if(updateUrl){const state=new URLSearchParams();if(cats.length)state.set('category',cats.join(','));if(term)state.set('search',search.value);if(sort.value!=='recommended')state.set('sort',sort.value);if(page>1)state.set('page',String(page));history.replaceState(null,'',location.pathname+(state.size?'?'+state.toString():''))}}
const reset=()=>{qa<HTMLInputElement>('input',catalogueRoot).forEach(i=>i.type==='checkbox'?i.checked=false:i.value='');sort.value='recommended';page=1;apply()};q('#clear-catalogue')?.addEventListener('click',reset);q('[data-reset-catalogue]')?.addEventListener('click',reset);catalogueRoot.addEventListener('input',()=>{page=1;apply()});sort.addEventListener('change',()=>{page=1;apply()});q('.filter-toggle')?.addEventListener('click',event=>{const b=event.currentTarget as HTMLButtonElement;const expanded=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(expanded));q('#catalogue-filters')!.classList.toggle('filters-open',expanded)});apply(false);
window.addEventListener('cta:catalogue',()=>{if(commerce.length){q('#price-filter')!.hidden=false;const ceiling=Math.ceil(Math.max(...commerce.map(p=>p.priceCents))/100);for(const kind of ['min','max']){const slider=q<HTMLInputElement>(`#${kind}-price-range`)!;slider.max=String(ceiling);slider.value=kind==='max'?String(ceiling):'0';slider.addEventListener('input',()=>{q<HTMLInputElement>(`#${kind}-price`)!.value=slider.value;page=1;apply()})}qa<HTMLOptionElement>('option[value^="price-"]',sort).forEach(o=>o.disabled=false);const groups=q('#approved-facets')!;['Size','ATM','Axle type','Brake type','Body finish','Tipper type','Accessory type'].forEach(name=>{const values=[...new Set(commerce.map(p=>p.specifications[name]).filter(Boolean))];if(!values.length)return;const details=document.createElement('details');details.dataset.approvedFacet=name;details.append(node('summary',name));const options=node('div','','facet-options');values.forEach(value=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.value=value;label.append(input,node('span',value));options.append(label)});details.append(options);groups.append(details)});apply(false)}});
}
if(q('[data-price-for], [data-catalogue-root]'))fetch('/api/catalogue').then(async r=>{if(!r.ok)return;const data=await r.json();commerce=Array.isArray(data.products)?data.products:[];qa<HTMLElement>('[data-price-for]').forEach(el=>{const p=commerce.find(p=>p.id===el.dataset.priceFor&&p.enabled);if(p)el.textContent=`${money(p.priceCents)} incl. GST`});window.dispatchEvent(new Event('cta:catalogue'))}).catch(()=>{});

// Preserve the intent from support and product links in the shared enquiry workflow.
const quote=q<HTMLFormElement>('#quote-form');if(quote){const params=new URLSearchParams(location.search);const id=params.get('product');if(id&&findProduct(id))(quote.elements.namedItem('productId') as HTMLSelectElement).value=id;const topic=params.get('topic');if(topic){const message=quote.elements.namedItem('message') as HTMLTextAreaElement;if(!message.value)message.value=`I would like to ask about ${topic.replaceAll('-',' ')}.\n\n`;if(['fleet','business','dealer'].includes(topic))(quote.elements.namedItem('kind') as HTMLSelectElement).value=topic==='fleet'?'fleet':'business';if(topic==='delivery'||topic==='collection')(quote.elements.namedItem('fulfilment') as HTMLSelectElement).value=topic}}
qa('[data-review-next]').forEach(b=>b.addEventListener('click',()=>q('.review-track')?.scrollBy({left:380,behavior:'smooth'})));qa('[data-review-prev]').forEach(b=>b.addEventListener('click',()=>q('.review-track')?.scrollBy({left:-380,behavior:'smooth'})));

const configuration=q<HTMLFormElement>('#configuration');if(configuration){const update=()=>{q('[data-config-quantity]')!.textContent=(configuration.elements.namedItem('quantity') as HTMLInputElement).value;const fulfilment=configuration.elements.namedItem('fulfilment') as HTMLSelectElement;q('[data-config-fulfilment]')!.textContent=fulfilment.selectedOptions[0]?.textContent||''};configuration.addEventListener('input',update);update();}
const selectionExport=q<HTMLButtonElement>('#export-selection');selectionExport?.addEventListener('click',()=>{const items=readCart();const lines=['CAR TRAILERS AUSTRALIA — Trailer enquiry','',...items.map(i=>`${findProduct(i.productId)!.name} × ${i.quantity}\nRequirements: ${i.requirements||'To discuss'}\nFulfilment: ${i.fulfilment}\n`),'Prices, specifications and availability require confirmation.'];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='car-trailers-enquiry.txt';a.click();URL.revokeObjectURL(url)});
if(quote){const topic=quote.dataset.topic;if(topic&&!new URLSearchParams(location.search).has('topic')){const message=quote.elements.namedItem('message') as HTMLTextAreaElement;if(!message.value)message.value=`I would like to ask about ${topic}.\n\n`;if(topic==='fleet'||topic==='dealer')(quote.elements.namedItem('kind') as HTMLSelectElement).value=topic==='fleet'?'fleet':'business'}
fetch('/api/public-settings').then(async r=>{if(!r.ok)return;const settings=await r.json();q<HTMLButtonElement>('button[type=submit]',quote)!.disabled=!settings.enquiriesEnabled;if(!settings.enquiriesEnabled){const notice=q('#enquiry-availability')!;notice.hidden=false;notice.textContent='Online enquiries are not open yet. You can prepare and download your enquiry details; nothing will be sent.';const submit=q<HTMLButtonElement>('button[type=submit]',quote)!;submit.disabled=true;submit.textContent='Online enquiries opening soon'}}).catch(()=>{});
q('#download-enquiry')?.addEventListener('click',()=>{const data=new FormData(quote);const labels:Record<string,string>={name:'Name',email:'Email',phone:'Phone',postcode:'Postcode',productId:'Trailer interest',kind:'Enquiry type',fulfilment:'Fulfilment',message:'Requirements',company:'Company'};const lines=['CAR TRAILERS AUSTRALIA — Enquiry draft','This draft has not been sent.',''];Object.entries(labels).forEach(([key,label])=>{const value=String(data.get(key)||'');if(value)lines.push(`${label}: ${key==='productId'?(findProduct(value)?.name||'Custom / help me choose'):value}`)});const url=URL.createObjectURL(new Blob([lines.join('\n\n')],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='car-trailers-enquiry-draft.txt';a.click();URL.revokeObjectURL(url)})}
q<HTMLInputElement>('#manual-search')?.addEventListener('input',event=>{const term=(event.currentTarget as HTMLInputElement).value.toLowerCase().trim();const documents=qa<HTMLElement>('[data-manual]');documents.forEach(link=>link.hidden=!link.dataset.manual!.includes(term));q('#manual-empty')!.hidden=documents.some(link=>!link.hidden)});
