import {test} from 'node:test';
import assert from 'node:assert/strict';
import Stripe from 'stripe';
import {priceOrder,checkoutSchema} from '../src/lib/pricing';
import {applySession,checkoutSession,receiveWebhook,orderForCookie,applyRefund,type Order} from '../src/lib/commerce';
import {submitQuote} from '../src/lib/quotes';
import {staff} from '../src/lib/auth';
import {sample,database,environment,request,seed} from './helpers';
const input=(change:Record<string,unknown>={})=>checkoutSchema.parse({requestKey:crypto.randomUUID(),email:'test@example.test',items:[{productId:sample.id,quantity:1,optionIds:['rack'],revision:1}],paymentMode:'full',fulfilment:'collection',collectionId:'test-depot',expectedTotalCents:1015000,...change});
test('full payment includes itemised extras and collection in exact AUD cents',()=>{const p=priceOrder(input(),[sample]);assert.equal(p.totalCents,1015000);assert.equal(p.dueCents,1015000);assert.equal(p.balanceCents,0)});
test('approved percentage deposit applies to complete configured line',()=>{const p=priceOrder(input({paymentMode:'deposit'}),[sample]);assert.equal(p.dueCents,203000);assert.equal(p.balanceCents,812000)});
test('fixed deposit multiplies per trailer and never silently becomes full payment',()=>{const p={...sample,deposit:{type:'fixed' as const,cents:150000}};const i=input({items:[{productId:sample.id,quantity:2,revision:1,optionIds:[]}],expectedTotalCents:2010000,paymentMode:'deposit'});assert.equal(priceOrder(i,[p]).dueCents,300000);assert.throws(()=>priceOrder(i,[{...p,deposit:{type:'fixed',cents:2000000}}]),/invalid/)});
test('manipulated total, stale revision, unknown and incompatible options are rejected',()=>{assert.throws(()=>priceOrder(input({expectedTotalCents:1}),[sample]),/total has changed/);assert.throws(()=>priceOrder(input({items:[{productId:sample.id,quantity:1,revision:2,optionIds:[]}]}),[sample]),/configuration has changed/);assert.throws(()=>priceOrder(input({items:[{productId:sample.id,quantity:1,revision:1,optionIds:['unknown']}]}),[sample]),/option is no longer/);assert.throws(()=>priceOrder(input({items:[{productId:sample.id,quantity:1,revision:1,optionIds:['rack','cover']}]}),[sample]),/cannot be combined/)});
test('unconfirmed freight and disabled products cannot be charged',()=>{assert.equal(checkoutSchema.safeParse({...input(),fulfilment:'delivery'}).success,false);assert.throws(()=>priceOrder(input(),[{...sample,enabled:false}]),/confirmed quote/)});
function stripeMock(){const original=globalThis.fetch;let count=0;const sessions=new Map<string,any>();globalThis.fetch=async(url,init)=>{const target=String(url);assert.ok(target.startsWith('https://api.stripe.com/'),'Unexpected network request in test');if(init?.method==='POST'&&target.endsWith('/v1/checkout/sessions')){const data=new URLSearchParams(String(init.body));const id=`cs_test_${++count}`;const session={id,object:'checkout.session',url:`https://checkout.stripe.com/c/pay/${id}`,status:'open',payment_status:'unpaid',currency:'aud',amount_total:Number(data.get('line_items[0][price_data][unit_amount]')),metadata:{orderId:data.get('metadata[orderId]'),checkoutId:data.get('metadata[checkoutId]')},client_reference_id:data.get('client_reference_id'),payment_intent:`pi_${id}`};sessions.set(id,session);return Response.json(session);}const session=sessions.get(target.split('/').pop()!);assert.ok(session,'Unknown session');return Response.json(session)};return{sessions,restore:()=>{globalThis.fetch=original},count:()=>count}}
async function pending(){const d=database();await seed(d.db);const e=environment(d.db);const mock=stripeMock();const response=await checkoutSession(request('/api/checkout',input({paymentMode:'deposit'})),e);const result=await response.json();const order=(await d.db.prepare('SELECT * FROM orders WHERE id=?').bind(result.reference).first<Order>())!;const session=Array.from(mock.sessions.values())[0];return{...d,e,mock,response,order,session};}
test('Stripe session creation reserves inventory and immutable configuration, cookie protects order',async()=>{const c=await pending();try{assert.equal((await c.db.prepare('SELECT available FROM inventory').first<any>()).available,1);assert.equal(c.order.due_cents,203000);const cookie=c.response.headers.get('set-cookie')!.split(';')[0];const order=await orderForCookie(new Request('https://preview.example.test/api/order',{headers:{Cookie:cookie}}),c.e);assert.equal(order.id,c.order.id);await assert.rejects(()=>orderForCookie(new Request('https://preview.example.test/api/order'),c.e),/browser you used/);assert.equal(JSON.parse(c.order.snapshot).lines[0].options[0].id,'rack')}finally{c.mock.restore();c.close()}});
test('duplicate payment notifications produce one settled payment and one outbox receipt',async()=>{const c=await pending();try{c.session.payment_status='paid';c.session.status='complete';await applySession(c.e,c.session,'evt_one','checkout.session.completed');await applySession(c.e,c.session,'evt_one','checkout.session.completed');await applySession(c.e,c.session,'evt_two','checkout.session.completed');const o=(await c.db.prepare('SELECT * FROM orders').first<Order>())!;assert.equal(o.paid_cents,203000);assert.equal(o.payment_status,'deposit_received');assert.equal(o.reservation_state,'captured');assert.equal((await c.db.prepare('SELECT COUNT(*) AS count FROM outbox').first<any>()).count,1);assert.equal((await c.db.prepare('SELECT available FROM inventory').first<any>()).available,1)}finally{c.mock.restore();c.close()}});
test('expired unpaid sessions release stock exactly once',async()=>{const c=await pending();try{c.session.status='expired';await applySession(c.e,c.session,'evt_expired','checkout.session.expired');await applySession(c.e,c.session,'evt_expired','checkout.session.expired');assert.equal((await c.db.prepare('SELECT available FROM inventory').first<any>()).available,2);assert.equal((await c.db.prepare('SELECT payment_status FROM orders').first<any>()).payment_status,'expired')}finally{c.mock.restore();c.close()}});
test('signature validation rejects forged callbacks, and stale event uses current Stripe state',async()=>{const c=await pending();try{await assert.rejects(()=>receiveWebhook(new Request('https://preview.example.test/api/stripe/webhook',{method:'POST',headers:{'stripe-signature':'bad'},body:'{}'}),c.e),/Invalid notification/);c.session.payment_status='paid';c.session.status='complete';const event={id:'evt_stale',type:'checkout.session.expired',livemode:false,data:{object:{id:c.session.id}}};const payload=JSON.stringify(event);const signature=Stripe.webhooks.generateTestHeaderString({payload,secret:c.e.STRIPE_WEBHOOK_SECRET!});await receiveWebhook(new Request('https://preview.example.test/api/stripe/webhook',{method:'POST',headers:{'stripe-signature':signature},body:payload}),c.e);assert.equal((await c.db.prepare('SELECT payment_status FROM orders').first<any>()).payment_status,'deposit_received')}finally{c.mock.restore();c.close()}});
test('session amount mismatch never marks order paid',async()=>{const c=await pending();try{await assert.rejects(()=>applySession(c.e,{...c.session,amount_total:1,payment_status:'paid'},'evt_bad','checkout.session.completed'),/snapshot_mismatch/);assert.equal((await c.db.prepare('SELECT paid_cents FROM orders').first<any>()).paid_cents,0)}finally{c.mock.restore();c.close()}});
test('simultaneous attempts for the final unit cannot oversell',async()=>{const d=database();await seed(d.db,{...sample,stock:1});const e=environment(d.db);const mock=stripeMock();try{const results=await Promise.allSettled([checkoutSession(request('/api/checkout',input()),e),checkoutSession(request('/api/checkout',input()),e)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await d.db.prepare('SELECT available FROM inventory').first<any>()).available,0);assert.equal((await d.db.prepare('SELECT COUNT(*) AS count FROM orders').first<any>()).count,1)}finally{mock.restore();d.close()}});
test('same checkout request reuses order and Stripe session',async()=>{const d=database();await seed(d.db);const e=environment(d.db),mock=stripeMock(),i=input();try{await checkoutSession(request('/api/checkout',i),e);await checkoutSession(request('/api/checkout',i),e);assert.equal(mock.count(),1);assert.equal((await d.db.prepare('SELECT COUNT(*) AS count FROM orders').first<any>()).count,1)}finally{mock.restore();d.close()}});
test('quote capture is durable and disabled launch gate rejects external data',async()=>{const d=database(),e=environment(d.db);try{const payload={name:'Test Customer',email:'test@example.test',postcode:'2000',productId:sample.id,kind:'business',fulfilment:'delivery',message:'TEST ONLY equipment request',consent:true};const response=await submitQuote(request('/api/quotes',payload),e);assert.equal(response.status,201);assert.equal((await d.db.prepare('SELECT COUNT(*) AS count FROM quotes').first<any>()).count,1);await assert.rejects(()=>submitQuote(request('/api/quotes',payload),{...e,ENQUIRIES_ENABLED:'false'}),/being connected/);await assert.rejects(()=>submitQuote(new Request('https://preview.example.test/api/quotes',{method:'POST',headers:{Origin:'https://attacker.example','Content-Type':'application/json'},body:JSON.stringify(payload)}),e),/must come from/)}finally{d.close()}});
test('staff API has no fallback identity or unverified header bypass',async()=>{const d=database();try{await assert.rejects(()=>staff(new Request('https://preview.example.test/admin',{headers:{'Cf-Access-Authenticated-User-Email':'owner@example.test'}}),environment(d.db)),/not been connected/)}finally{d.close()}});
test('refund notifications are recorded once without silently restocking',async()=>{const c=await pending();try{c.session.payment_status='paid';c.session.status='complete';await applySession(c.e,c.session,'evt_pay','checkout.session.completed');const refund={id:'re_test',amount:50000,payment_intent:c.session.payment_intent,status:'succeeded',reason:'requested_by_customer'} as Stripe.Refund;await applyRefund(c.e,refund,'evt_refund');await applyRefund(c.e,refund,'evt_refund');const o=(await c.db.prepare('SELECT * FROM orders').first<Order>())!;assert.equal(o.refunded_cents,50000);assert.equal(o.payment_status,'partially_refunded');assert.equal((await c.db.prepare('SELECT available FROM inventory').first<any>()).available,1)}finally{c.mock.restore();c.close()}});
test('balance settlement completes a deposit order without reserving stock twice',async()=>{const c=await pending();try{c.session.payment_status='paid';c.session.status='complete';await applySession(c.e,c.session,'evt_deposit','checkout.session.completed');const balanceId=`${c.order.id}:balance`;await c.db.prepare("INSERT INTO checkouts(id,order_id,kind,amount_cents,session_id,created_at) VALUES (?,?,'balance',?,'cs_balance',?)").bind(balanceId,c.order.id,812000,0).run();const session={...c.session,id:'cs_balance',payment_intent:'pi_balance',amount_total:812000,metadata:{orderId:c.order.id,checkoutId:balanceId}};await applySession(c.e,session,'evt_balance','checkout.session.completed');const o=(await c.db.prepare('SELECT * FROM orders').first<Order>())!;assert.equal(o.paid_cents,o.total_cents);assert.equal(o.payment_status,'paid');assert.equal((await c.db.prepare('SELECT available FROM inventory').first<any>()).available,1)}finally{c.mock.restore();c.close()}});
test('replayed successful payment after refund preserves the refund status',async()=>{const c=await pending();try{c.session.payment_status='paid';c.session.status='complete';await applySession(c.e,c.session,'evt_pay_first','checkout.session.completed');await applyRefund(c.e,{id:'re_later',amount:50000,payment_intent:c.session.payment_intent,status:'succeeded'} as Stripe.Refund,'evt_refund_later');await applySession(c.e,c.session,'evt_pay_replayed','checkout.session.completed');assert.equal((await c.db.prepare('SELECT payment_status FROM orders').first<any>()).payment_status,'partially_refunded')}finally{c.mock.restore();c.close()}});
test('partial reservation failure rolls back every item and the draft order',async()=>{const d=database();await seed(d.db);await seed(d.db,{...sample,id:'compact-box',stock:0});const e=environment(d.db),mock=stripeMock();try{const i=input({items:[{productId:sample.id,quantity:1,optionIds:['rack'],revision:1},{productId:'compact-box',quantity:1,optionIds:[],revision:1}],expectedTotalCents:2020000});await assert.rejects(()=>checkoutSession(request('/api/checkout',i),e));assert.equal((await d.db.prepare('SELECT available FROM inventory WHERE product_id=?').bind(sample.id).first<any>()).available,2);assert.equal((await d.db.prepare('SELECT COUNT(*) AS count FROM orders').first<any>()).count,0)}finally{mock.restore();d.close()}});
